version: '3'
services:
  app:
    environment:
    - CONNSTR=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    - UPMEGRATE=schema/000001_init.up.sql
    build:
      context: .
      dockerfile: Dockerfile
    ports: # Проброс портов
      - "8080:8080"
    depends_on:
    - db
  db:
    image: postgres:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports: # Проброс портов
     - "5432:5432"