version: '3'
services:
  app:
    environment:
    - CONNSTR=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    - MIGRATES=file://schema
    - PORT=:8080
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
    - db
  db:
    image: postgres:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
     - "5432:5432"
    init: true